biome:
  oceans: true
  plains: true
  desert: true
  desert-hills: true
  extreme-hills: true
  extreme-hills-plus: true
  forest: true
  forest-hills: true
  taiga: true
  taiga-hills: true
  swampland: true
  ice-plains: true
  ice-mountains: true
  mushroom-island: true
  jungle: true
  jungle-hills: true
  birch-forest: true
  birch-forest-hills: true
  roofed-forest: true
  cold-taiga: true
  cold-taiga-hills: true
  mega-taiga: true
  mega-taiga-hills: true
  savanna: true
  savanna-plateau: true
  mesa: true
  mesa-plateau-f: true
  mesa-plateau: true
  center:
    radius: 0
    biome: plains
    removeRivers: false
cave:
  generateRate: 12
  largeCaveGenerateRate: 20
  caveMinAltitude: 8
  caveMaxAltitude: 120
sugarCane:
  round: 10
  height_min: 2
  height_max: 5
stacker:
  enabled: false
  only_stack_spawner: false
  radius: 5.0
  max_stack_amount: 50
  ticks_to_stack: 100
  ignore_type:
  - HORSE
  - VILLAGER
  - WOLF
misc:
  disableCobbleGen: false
  disableObsidianGen: false
  spawnerSpawnMobsRegardlessLightLevel: false
  generateFarLands: false
  disableEnderpearlTravelExploit: false
  allowBlockPermanentBreakingExploits: false
entity:
  ticksPerWaterAnimalSpawns: 1
  ticksPerAmbientSpawns: 1
block:
  doBlockOperations: true
  randomBlockTickSkipping: 500
  maxDistanceChunkToTick: 3
hopper:
  cooldownHopperWhenFull: true
  disableHopperMoveEvents: false
ores:
  diamond:
    type: 56
    chance: 0.25
    minHeight: 0
    maxHeight: 32
    size: 8
    round: 1
